name: JstHack
author: Cosmin Haims
description: UI & UX | Product Design | Front-End Dev
meta_description: "Personal Blog, Product Design, User Experience, User Interface Design, Ui, Ux, Graphic Design, Front-End development, git, github, node.js, css, html, css tutorial, javascript, Front-End tutorial, deign blog"


markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://jsthack.github.io'
google_analytics: 'UA-102062590-1'
plugins: [jekyll-paginate]

#gems:
#   - jekyll-seo-tag

# Details for the RSS feed generator
url:            'blog url'
author:         'Cosmin Haims'
