name: JstHack BLog
description: UI & UX | Product Design | Front-End Dev
meta_description: "Cosmin Haims's personal blog about product design, ui, user experience, and fron-end development. "

markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://jsthack.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
